/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyectointermodular;

import dao.BaseDeDatosUsuarios;
import emailService.EmailSender;
import encriptadoSym.EncriptadoCipher;
import javax.swing.JOptionPane;
import pojos.Usuario;

/**
 *
 * @author javib
 */
public class InsertarPassPag extends javax.swing.JInternalFrame {
    BaseDeDatosUsuarios base=new BaseDeDatosUsuarios();
    String userSesion = null;
    //Para AES 16 bits
    String pass = "1234567812345678";
    /**
     * Creates new form InsertarPassPag
     */
    public InsertarPassPag() {
        initComponents();
        TextPrompt nombreprompt = new TextPrompt("Nombre de la Página", nombrePagjTextField);
        TextPrompt urlprompt = new TextPrompt("Url completa", urljTextField);
        TextPrompt userprompt = new TextPrompt("Nombre de Usuario", nombreUsuerjTextField);
        TextPrompt passprompt = new TextPrompt("Contraseña", passWordjTextField);
        
    }
    
    public InsertarPassPag(String userSesion) {
        initComponents();
        TextPrompt nombreprompt = new TextPrompt("Nombre de la Página", nombrePagjTextField);
        TextPrompt urlprompt = new TextPrompt("Url completa", urljTextField);
        TextPrompt userprompt = new TextPrompt("Nombre de Usuario", nombreUsuerjTextField);
        TextPrompt passprompt = new TextPrompt("Contraseña", passWordjTextField);
        System.out.println("este es el usuario de la sesión"+userSesion);
        this.userSesion = userSesion;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombrePaginajLabel = new javax.swing.JLabel();
        urlPaginajLabel = new javax.swing.JLabel();
        nombreUserjLabel = new javax.swing.JLabel();
        passWordjLabel = new javax.swing.JLabel();
        nombrePagjTextField = new javax.swing.JTextField();
        urljTextField = new javax.swing.JTextField();
        nombreUsuerjTextField = new javax.swing.JTextField();
        passWordjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        guardarPagjButton1 = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nombrePaginajLabel.setText("Nombre_Página");

        urlPaginajLabel.setText("Url_Página");

        nombreUserjLabel.setText("Nombre_Usuario");

        passWordjLabel.setText("Password");

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("GUARDA TUS PÁGINAS CON CONTRASEÑA");

        guardarPagjButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        guardarPagjButton1.setText("Guardar");
        guardarPagjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarPagjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nombreUserjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(urlPaginajLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombrePaginajLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passWordjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guardarPagjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(passWordjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                        .addComponent(nombreUsuerjTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(urljTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nombrePagjTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePaginajLabel)
                    .addComponent(nombrePagjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlPaginajLabel)
                    .addComponent(urljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreUserjLabel)
                    .addComponent(nombreUsuerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passWordjLabel)
                    .addComponent(passWordjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(guardarPagjButton1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarPagjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarPagjButton1ActionPerformed
        // TODO add your handling code here: 
        Integer id = base.obtenerUsuarioLoginPorCriterio(userSesion);
        Usuario user = new Usuario();
        user.setNombre(nombrePagjTextField.getText());
        user.setUrl(urljTextField.getText());
        user.setNombreUser(nombreUsuerjTextField.getText());
        EncriptadoCipher encript = new EncriptadoCipher();
        String encriptada = encript.encriptar(passWordjTextField.getText(), pass);
        user.setPassword(encriptada);
        base.insertarUsuarioPagina(user,id);
        JOptionPane.showMessageDialog(this, "El password de la pagina "+urljTextField.getText()+" ha sido mandado a la BBDD");
        

    }//GEN-LAST:event_guardarPagjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardarPagjButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nombrePaginajLabel;
    private javax.swing.JTextField nombrePagjTextField;
    private javax.swing.JLabel nombreUserjLabel;
    private javax.swing.JTextField nombreUsuerjTextField;
    private javax.swing.JLabel passWordjLabel;
    private javax.swing.JTextField passWordjTextField;
    private javax.swing.JLabel urlPaginajLabel;
    private javax.swing.JTextField urljTextField;
    // End of variables declaration//GEN-END:variables
}
