/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectointermodular;

import dao.BaseDeDatosUsuarios;
import emailService.EmailSender;
import encriptadoSym.EncriptadoCipher;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pojos.Usuario;
import pojos.UsuarioPassword;

/**
 *
 * @author javib
 */
public class PasswordRegistro extends javax.swing.JFrame {

    BaseDeDatosUsuarios base=new BaseDeDatosUsuarios();
    //Para AES 16 bits
    String pass = "1234567812345678";
    
    public PasswordRegistro() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Formulario Login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usuarioRegistrojTextField = new javax.swing.JTextField();
        emailRegistrojTextField = new javax.swing.JTextField();
        contrasenaRegistrojTextField = new javax.swing.JTextField();
        registroUserPasswordjButton = new javax.swing.JButton();
        returnLoginjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO PASSWORD");

        jLabel2.setText("Nombre ");

        jLabel3.setText("Email");

        jLabel4.setText("Contraseña");

        emailRegistrojTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailRegistrojTextFieldActionPerformed(evt);
            }
        });

        registroUserPasswordjButton.setText("Registrate");
        registroUserPasswordjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroUserPasswordjButtonActionPerformed(evt);
            }
        });

        returnLoginjButton.setText("Volver Login");
        returnLoginjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnLoginjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(registroUserPasswordjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(returnLoginjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(emailRegistrojTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usuarioRegistrojTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contrasenaRegistrojTextField))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usuarioRegistrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(emailRegistrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(contrasenaRegistrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registroUserPasswordjButton)
                    .addComponent(returnLoginjButton))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailRegistrojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailRegistrojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailRegistrojTextFieldActionPerformed

    private void returnLoginjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnLoginjButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Vuelvo a LOGIN");
        Principal ppal = new Principal();
        ppal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnLoginjButtonActionPerformed

    private void registroUserPasswordjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroUserPasswordjButtonActionPerformed
        // TODO add your handling code here:
        UsuarioPassword userReg = new UsuarioPassword();
        userReg.setUsuarioNombre(usuarioRegistrojTextField.getText());
        userReg.setUsuarioEmail(emailRegistrojTextField.getText());
        //userReg.setUsuarioPassword(contrasenaRegistrojTextField.getText());
        // Para encriptar el password en la BBDD.
        EncriptadoCipher encript = new EncriptadoCipher();
        String encriptada = encript.encriptar(contrasenaRegistrojTextField.getText(), pass);
        userReg.setUsuarioPassword(encriptada);
        base.insertUsuarioPassword(userReg);
        JOptionPane.showMessageDialog(this, "El usuario"+usuarioRegistrojTextField.getText()+" ha sido registrado a la BBDD");
        // Creo el hilo para enviar el email al usuario que se ha registrado
        Thread userEmailThread = new Thread(new EmailSender(emailRegistrojTextField.getText(), 
                                                        "Bienvenido " + usuarioRegistrojTextField.getText(), 
                                                        "Tu registro ha sido exitoso."));
        // Creo el hilo para enviar el email al administrador con el usuario que se ha registrado
        Thread adminEmailThread =new Thread(new EmailSender("admin@example.com", "Nuevo usuario registrado", "Se ha registrado el usuario: " + usuarioRegistrojTextField.getText()));
                System.out.println("Correo enviado al administrador.");

        // Iniciar los hilos
        userEmailThread.start();
        adminEmailThread.start();
        
        try {
            userEmailThread.join();
            adminEmailThread.join();
        } catch (InterruptedException ex) {
            Logger.getLogger(PasswordRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        System.out.println("este es el nombre del hilo"+userEmailThread.getName());
        System.out.println("este es el nombre del hilo"+adminEmailThread.getName());
    }//GEN-LAST:event_registroUserPasswordjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contrasenaRegistrojTextField;
    private javax.swing.JTextField emailRegistrojTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registroUserPasswordjButton;
    private javax.swing.JButton returnLoginjButton;
    private javax.swing.JTextField usuarioRegistrojTextField;
    // End of variables declaration//GEN-END:variables
}
