/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectointermodular;

import dao.BaseDeDatosUsuarios;
import emailService.EmailSender;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import pojos.Usuario;

/**
 *
 * @author javib
 */
public class pruebaFormulario extends javax.swing.JFrame {
    BaseDeDatosUsuarios base=new BaseDeDatosUsuarios();
    DefaultTableModel modeloTabla = new DefaultTableModel();
    Usuario usuarioSeleccionado =null;
    String userPag = null;
    /**
     * Creates new form pruebaFormulario
     */
    public pruebaFormulario() {
        initComponents();
        //jPanel1.setVisible(true);
        //jPanel2.setVisible(false);
        //buscarUserLabel.setVisible(false);
        //cargarColumnasTablas();
        //cargarModeloTabla();
        /*TextPrompt nombreprompt = new TextPrompt("Nombre", nombreText);
        TextPrompt apellidoprompt = new TextPrompt("Apellidos", apellidosText);
        TextPrompt emailprompt = new TextPrompt("Email", emailText);
        TextPrompt telef = new TextPrompt("Teléfono", telefonoText);*/
    }
        public pruebaFormulario(String usuarioPagina) {
        initComponents();
        //jPanel1.setVisible(true);
        //jPanel2.setVisible(false);
        //buscarUserLabel.setVisible(false);
        //cargarColumnasTablas();
        //cargarModeloTabla();
        /*TextPrompt nombreprompt = new TextPrompt("Nombre", nombreText);
        TextPrompt apellidoprompt = new TextPrompt("Apellidos", apellidosText);
        TextPrompt emailprompt = new TextPrompt("Email", emailText);
        TextPrompt telef = new TextPrompt("Teléfono", telefonoText);*/
        this.userPag = usuarioPagina; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        insertPassButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("GUARDA TUS PASSWORD");

        insertPassButton.setText("InsertarPassword");
        insertPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertPassButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Actualización");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertPassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(insertPassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1084, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 967, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
InsertarPassPag instPass;
    private void insertPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertPassButtonActionPerformed
    // TODO add your handling code here:
            if (instPass == null) {
            instPass = new InsertarPassPag(userPag);
            jDesktopPane1.add(instPass);
            jDesktopPane1.getDesktopManager().maximizeFrame(instPass);
            instPass.setVisible(true);
        } else {
            jDesktopPane1.getDesktopManager().maximizeFrame(instPass);
            
        }
    
    }//GEN-LAST:event_insertPassButtonActionPerformed
UpdatePassPag updatePass;
    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        if (updatePass == null) {
            Integer userSesionId = base.obtenerUsuarioLoginPorCriterio(userPag);
            updatePass = new UpdatePassPag(userSesionId);
            jDesktopPane1.add(updatePass);
            jDesktopPane1.getDesktopManager().maximizeFrame(updatePass);
            updatePass.setVisible(true);
        } else {
            jDesktopPane1.getDesktopManager().maximizeFrame(updatePass);
            
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed
    /**
     * Este metodo carga el modelo de la Tabla de inventarios*
     */
    private void cargarColumnasTablas(){
        modeloTabla.addColumn("id");
        modeloTabla.addColumn("nombre");
        modeloTabla.addColumn("apellidos");
        modeloTabla.addColumn("email");
        modeloTabla.addColumn("telefono");
    }
    private void cargarModeloTabla() {

       /* System.out.println("EStoy en cargar modelo tabla");
        limpiarTabla();
        ArrayList <Usuario> listaUsuarios=base.obtenerUsuarios();
        int numeroUsuarios= listaUsuarios.size();
        System.out.println("EStoy en cargar modelo tabla"+numeroUsuarios);
        modeloTabla.setNumRows(numeroUsuarios);
        
        for (int i = 0; i < listaUsuarios.size(); i++) {
            Usuario user = listaUsuarios.get(i);
            Integer clave = user.getIdUser();
            String nombre = user.getNombre();
            String apellido = user.getApellidos();
            String telefono = user.getPhone();
            String email = user.getEmail();
            modeloTabla.setValueAt(clave, i, 0);
            modeloTabla.setValueAt(nombre, i, 1);
            modeloTabla.setValueAt(apellido, i, 2);
            modeloTabla.setValueAt(email, i, 3);
            //modeloTabla.setValueAt(precioVenta, i, 4);
            modeloTabla.setValueAt(telefono, i, 4);
        }*/

    }
    
    private void limpiarTabla() {
        int numFilas= modeloTabla.getRowCount();
        System.out.println("nume fillas : "+numFilas);
        if (numFilas>0) {
            for (int i = numFilas-1; i >=0 ; i--) {
            modeloTabla.removeRow(i);
            
            }
        }    

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pruebaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pruebaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pruebaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pruebaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pruebaFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton insertPassButton;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
